setPartner: remove new partner from homeDigimonList
Not doing this causes ClientError upon attempting to enter DigiTown:

    ArgumentException: An item with the same key has already been added. Key: 123456789
       at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert(TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior)
       at UnityApplication.HomeAPIRequester.LoadHomeDigimonList(UnityApplication.API.UserData userData)
       at UnityApplication.HomeAPIRequester.LoadHomeInfo(UnityApplication.API.UserData userData, UnityApplication.HomeInfo info)
       at UnityApplication.HomeAPIRequester+<LoadOwnHomeInfo>d__0.MoveNext()
       at UnityEngine.SetupCoroutine.InvokeMoveNext(System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress)